### ISSUE TITLE
Use HTML in 'help_text' of model fields

### ISSUE THREAD

**Issue by petrikoz** [ITCase-django/django-unisender#39]
Now this is looking bad:

> Если 0, то мы считаем, что подписчик только высказал желание подписаться, но ещё не подтвердил подписку. В этом случае подписчику будет отправлено письмо-приглашение подписаться. Текст письма будет взят из свойств первого списка из list_ids. Кстати, текст можно поменять с помощью метода updateOptInEmail или через веб-интерфейс. Если 1, то мы считаем, что у Вас уже есть согласие подписчика. Но при этом для защиты от злоупотреблений есть суточный лимит подписок. Если он не превышен, мы не посылаем письмо-приглашение. Если же он превышен, подписчику высылается письмо с просьбой подтвердить подписку. Текст этого письма можно настроить для каждого списка с помощью метода updateOptInEmail или через веб-интерфейс. Лимиты мы согласовываем в индивидуальном порядке. Если 2, то также считается, что у Вас согласие подписчика уже есть, но в случае превышения лимита мы возвращаем код ошибки too_many_double_optins. Если 3, то также считается, что у Вас согласие подписчика уже есть, но в случае превышения лимита подписчик добавляется со статусом «новый».

For more detail see [Django docs](https://docs.djangoproject.com/en/dev/ref/models/fields/#help-text).

**Comment by mr-africa** [comment]
Arcady can implement this task
